conditioning:
  method: ps
  params:
    scale: 1.7

data:
  name: bedroom # choices: ffhq, bedroom, cat, celeba-hq
  root: ./data/samples_bedroom/ # address to put the associated images

measurement:
  operator:
    name: denoise
    in_shape: !!python/tuple [1, 3, 256, 256]
  
  noise: 
    name: gaussian
    sigma: 0.5
