conditioning:
  method: pgdm
  params:
    scale: 0.9
data:
  name: ffhq # choices: ffhq, bedroom, cat, celeba-hq
  root: ./data/samples/ # address to put the associated images

measurement:
  operator:
    name: deblur
    type: uniform
    kernel_size: 9
    intensity: 3.0
  
  noise: 
    name: gaussian
    sigma: 0.05
