conditioning:
  method: pgdm
  params:
    scale: 2.5

data:
  name: ffhq # choices: ffhq, bedroom, cat, celeba-hq
  root: ./data/samples/ # address to put the associated images

measurement:
  operator:
    name: inpainting
  mask_opt:
    mask_type: random
    # mask_len_range: !!python/tuple [128, 129]  # for box
    mask_prob_range: !!python/tuple [0.9, 0.9]  # for random
    image_size: 256


  noise:
    name: gaussian
    sigma: 0.05
