conditioning:
  method: pgdm
  params:
    scale: 1.1
    #scale: 1

data:
  name: ffhq # choices: ffhq, bedroom, cat, celeba-hq
  root: ./data/samples/ # address to put the associated images

measurement:
  operator:
    name: inpainting
  mask_opt:
    mask_type: box
    mask_len_range: !!python/tuple [128, 129]  # for box
    # mask_prob_range: !!python/tuple [0.3, 0.7]  # for random
    image_size: 256


  noise:
    name: gaussian
    sigma: 0.5
